# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
