# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_inventoryitem'),
        ('carts', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('cart', 'item')]),
        ),
    ]
