# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-votes']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-votes']},
        ),
    ]
