# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-18 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
      migrations.RenameField('Review', 'reviewer_name', 'author'),
    ]
