# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-votes']},
        ),
    ]
